# Scaffolding generated by Casein v5.1.1.5

module Casein
  class EmployeesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Employees'
  		@employees = Employee.order(sort_order(:name)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View employee'
      @employee = Employee.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new employee'
    	@employee = Employee.new
    end

    def create
      @employee = Employee.new employee_params
    
      if @employee.save
        flash[:notice] = 'Employee created'
        redirect_to casein_employees_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new employee'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update employee'
      
      @employee = Employee.find params[:id]
    
      if @employee.update_attributes employee_params
        flash[:notice] = 'Employee has been updated'
        redirect_to casein_employees_path
      else
        flash.now[:warning] = 'There were problems when trying to update this employee'
        render :action => :show
      end
    end
 
    def destroy
      @employee = Employee.find params[:id]

      @employee.destroy
      flash[:notice] = 'Employee has been deleted'
      redirect_to casein_employees_path
    end
  
    private
      
      def employee_params
        params.require(:employee).permit(:name, :description, :email, :phone)
      end

  end
end