# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fc856d84b9b41923b68819dbe23591f7b027131396d10c8db479e8ef797df452c21b1fbac3e60b59e918d429c31dc14502124f3ad11f13736e9ae8251e17f86

test:
  secret_key_base: e3aea81e6179cf8a04e5cfe896566eed8c82ec171da184c0917a391487e2a2c2ae88d76a09177ab5e10be886325f2c592532cdff1d565e60b04319cf6ed841a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
